### ISSUE TITLE
children is not a function error using with Gatsbyjs

### ISSUE THREAD

**Issue by lewiss444** [makotot/GhostUI#117] opened 2021-10-05 05:44 UTC
Got the following error:

Error in function Scrollspy in ./node_modules/@makotot/ghostui/dist/ghostui.esm.js:438
children is not a function

./node_modules/@makotot/ghostui/dist/ghostui.esm.js:438

` 436 |       currentElementIndexInViewport = _useScrollspy.currentElementIndexInViewport;
  437 |
> 438 |   return children({
  439 |     elementsStatusInViewport: elementsStatusInViewport,
  440 |     currentElementIndexInViewport: currentElementIndexInViewport
  441 |   });`

**Comment by makotot** [comment] 2021-11-01 15:49
It looks like you are probably using it incorrectly. 
Please check here for more information on how to use it.
https://ghostui.netlify.app/Scrollspy

If checking here doesn't seem to solve the problem, can you give me the code to reproduce it?
I close this issue, but feel free to reopen it.

**Closed by makotot** 2021-11-01 15:49 UTC
